AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 82

Layout/SpaceAroundOperators:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  CountComments: true
  Max: 25
  IgnoredMethods: []
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

# { ... } for multi-line blocks is okay
Style/BlockDelimiters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/FormatStringToken:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Enabled: false
